title: Thomas Pearse   # your title
author: tpearse # your name
description: Business and technology # your description
avatar: /images/avatar.png # change avatar
twitter_handle: t_pearse

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"
gems: [jekyll-paginate]

# Comments
# disqus:
#   shortname: xxxx-xxxxx-xxx   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics


exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
