title: Thomas Pearse   # your title
author: tpearse # your name
description: Personal log about business, technology and investing.  # your description
twitter_handle: t_pearse
twitter:username: t_pearse # For Jekyll SEO
twitter:username: card # For Jekyll SEO

# Build Settings
markdown: kramdown
highlighter: rouge


# SEO tag
plugins: [jekyll-seo-tag]

# Pagination
paginate: 5
paginate_path: "/page:num/"
plugins: [jekyll-paginate]


defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
# Comments
# disqus:
#   shortname: xxxx-xxxxx-xxx   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics


exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']



